workflows:
  version: 2
  test_build:
      jobs:
        - test
        - dockerize:
            requires:
              - test
        - deploy:
            requires:
              - dockerize

jobs:
  test:
    docker:  
      # docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: chandrarai/pythonapp:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

             
      - store_artifacts:
           path: .
           destination: test_output
             
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKERHUBUSERNAME -p $DOCKERPASS

      # build the application image
      - run: docker build -t $DOCKERHUBUSERNAME/flask-app-repo:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKERHUBUSERNAME/flask-app-repo:$CIRCLE_SHA1
   
  deploy:
    machine: true
    steps:
      
      - run: docker pull chandrarai/cir_chandra:$CIRCLE_SHA1

      - run: docker run -p 8888:5000 --name cir_chandra chandrarai/cir_chandra:$CIRCLE_SHA
